#!/usr/bin/python3.5
# -*- coding: UTF-8 -*-
max=input('enter max value: ',) #中国的汉字 check UTF-8 
try:
    max=int(max)
    for i in range(1,max+1):
        digit_list=[str(j) for j in range (1,i+1)]
        if i%2 == 0: digit_list=digit_list[::-1]
        print ('-'.join(digit_list))
except ValueError: print("no number, try again");
