# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='article',
        ),
        migrations.AddField(
            model_name='person',
            name='article',
            field=models.ManyToManyField(to='page.Article'),
        ),
    ]
