# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_file_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_test',
        ),
    ]
