# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_delete_file_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='wage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
