# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20161122_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='work_begin',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
