# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_reporter_work_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='work_begin',
            field=models.DateField(auto_now_add=True),
        ),
    ]
